version: "3.8"

services:
  config-server:
    image: omisys-config-server:latest
    container_name: config-server
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SERVER_PORT: 8888

      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: ${GIT_URI}
      SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME: ${GIT_NAME}
      SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD: ${GIT_TOKEN}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 10s
      timeout: 3s
      retries: 5
    ports:
      - "8888:8888"
    networks:
      - omisys-network

  eureka-service:
    image: omisys-eureka-service:latest
    container_name: eureka-service
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SERVER_PORT: 19090
    networks:
      - omisys-network
    ports:
      - "19090:19090"

  user-service:
    image: omisys-user-service:latest
    container_name: user-service
    depends_on:
      - eureka-service
    environment:
      SPRING_PROFILES_ACTIVE: prod

      USER_MYSQL_DATABASE: ${USER_MYSQL_DATABASE}
      USER_MYSQL_USER: ${USER_MYSQL_USER}
      USER_MYSQL_PASSWORD: ${USER_MYSQL_PASSWORD}
      USER_MYSQL_ROOT_PASSWORD: ${USER_MYSQL_ROOT_PASSWORD}

    networks:
      - omisys-network

  auth-service:
    image: omisys-auth-service:latest
    container_name: auth-service
    depends_on:
      - eureka-service
    environment:
      SPRING_PROFILES_ACTIVE: prod

      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    networks:
      - omisys-network

  gateway:
    image: omisys-gateway-service:latest
    container_name: gateway-service
    depends_on:
      - eureka-service
    environment:
      MAX_ACTIVE_USERS: ${MAX_ACTIVE_USERS}
    ports:
      - "19091:19091"
    networks:
      - omisys-network

networks:
  omisys-network:
    external: true
