version: "3.8"

services:
  config-server:
    image: omisys-config-server:latest
    container_name: config-server
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SERVER_PORT: 8888

      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: ${GIT_URI}
      SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME: ${GIT_NAME}
      SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD: ${GIT_TOKEN}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 10s
      timeout: 3s
      retries: 5
    ports:
      - "8888:8888"
    networks:
      - omisys-network

  eureka-service:
    image: omisys-eureka-service:latest
    container_name: eureka-service
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SERVER_PORT: 19090
    networks:
      - omisys-network
    ports:
      - "19090:19090"

  user-service:
    image: omisys-user-service:latest
    container_name: user-service
    depends_on:
      - eureka-service
    environment:
      SPRING_PROFILES_ACTIVE: prod

      USER_MYSQL_DATABASE: ${USER_MYSQL_DATABASE}
      USER_MYSQL_USER: ${USER_MYSQL_USER}
      USER_MYSQL_PASSWORD: ${USER_MYSQL_PASSWORD}
      USER_MYSQL_ROOT_PASSWORD: ${USER_MYSQL_ROOT_PASSWORD}

    networks:
      - omisys-network

  auth-service:
    image: omisys-auth-service:latest
    container_name: auth-service
    depends_on:
      - eureka-service
    environment:
      SPRING_PROFILES_ACTIVE: prod

      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    networks:
      - omisys-network

  gateway-service:
    image: omisys-gateway-service:latest
    container_name: gateway-service
    depends_on:
      - eureka-service
    environment:
      MAX_ACTIVE_USERS: ${MAX_ACTIVE_USERS}
    ports:
      - "19091:19091"
    networks:
      - omisys-network

  product-service:
    image: omisys-product-service:latest
    container_name: product-service
    depends_on:
      - eureka-service
    environment:

      SPRING_PROFILES_ACTIVE: prod

      ELASTIC_FINGERPRINT: ${ELASTIC_FINGERPRINT}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}

      PRODUCT_MYSQL_DATABASE: ${PRODUCT_MYSQL_DATABASE}
      PRODUCT_MYSQL_USER: ${PRODUCT_MYSQL_USER}
      PRODUCT_MYSQL_PASSWORD: ${PRODUCT_MYSQL_PASSWORD}
      PRODUCT_MYSQL_ROOT_PASSWORD: ${PRODUCT_MYSQL_ROOT_PASSWORD}

      AWS_S3_ACCESS_KEY: ${AWS_S3_ACCESS_KEY}
      AWS_S3_SECRET_KEY: ${AWS_S3_SECRET_KEY}
      AWS_S3_REGION: ${AWS_S3_REGION}

    networks:
      - omisys-network

  order-service:
    image: omisys-order-service:latest
    container_name: order-service
    depends_on:
      - eureka-service
    environment:
      SPRING_PROFILES_ACTIVE: prod

      ORDER_MYSQL_DATABASE: ${ORDER_MYSQL_DATABASE}
      ORDER_MYSQL_USER: ${ORDER_MYSQL_USER}
      ORDER_MYSQL_PASSWORD: ${ORDER_MYSQL_PASSWORD}
      ORDER_MYSQL_ROOT_PASSWORD: ${ORDER_MYSQL_ROOT_PASSWORD}
    networks:
      - omisys-network

  payment-service:
    image: omisys-payment-service:latest
    container_name: payment-service
    depends_on:
      - eureka-service
    environment:
      SPRING_PROFILES_ACTIVE: prod

      PAYMENT_MYSQL_ROOT_PASSWORD: ${PAYMENT_MYSQL_ROOT_PASSWORD}
      PAYMENT_MYSQL_DATABASE: ${PAYMENT_MYSQL_DATABASE}
      PAYMENT_MYSQL_USER: ${PAYMENT_MYSQL_USER}
      PAYMENT_MYSQL_PASSWORD: ${PAYMENT_MYSQL_PASSWORD}

      TOSS_SECRET_KEY: ${TOSS_SECRET_KEY}

      PUBLIC_BASE_URL: ${PUBLIC_BASE_URL}
    networks:
      - omisys-network

networks:
  omisys-network:
    external: true
