version: "3.8"

services:
  config-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - FILE_DIRECTORY=./service/config/server
    container_name: config-server
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=${GIT_URI}
      - SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME=${GIT_NAME}
      - SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD=${GIT_TOKEN}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 10s
      timeout: 3s
      retries: 5
    ports:
      - "8888:8888"
    networks:
      - omisys-network

  eureka-service:
    container_name: eureka-service
    depends_on:
      config-server:
        condition: service_healthy
    env_file:
      - .env
    build:
      dockerfile: Dockerfile
      args:
        - FILE_DIRECTORY=./service/eureka/server
    networks:
      - omisys-network
    ports:
      - "19090:19090"

networks:
  omisys-network:
    external: true
