version: "3.8"

services:
  config-server:
    image: omisys-config-server:latest
    container_name: config-server
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8888
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=${GIT_URI}
      - SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME=${GIT_NAME}
      - SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD=${GIT_TOKEN}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 10s
      timeout: 3s
      retries: 5
    ports:
      - "8888:8888"
    networks:
      - omisys-network

  eureka-service:
    image: omisys-eureka-service:latest
    container_name: eureka-service
    depends_on:
      config-server:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=19090
    networks:
      - omisys-network
    ports:
      - "19090:19090"

  user-service:
    image: omisys-user-service:latest
    container_name: user-service
    depends_on:
      - eureka-service
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - omisys-network

networks:
  omisys-network:
    external: true
