spring:
  application:
    name: user

  config:
    import: "configserver:http://localhost:8888"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:19090/eureka/
  instance:
    prefer-ip-address: true
