spring:
  application:
    name: user

  config:
    uri: http://config-server:8888
    label: main

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-service:19090/eureka/
  instance:
    prefer-ip-address: true
