name: Eureka Service CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      # eureka 서버 코드 경로에 맞게 수정
      - "service/eureka/server/**"
      - "Dockerfile"
      - "docker-compose.yml"

jobs:
  build-and-deploy-eureka-service:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build eureka-service jar
        run: |
          cd /home/chanhoan/projects/omisys
          chmod +x gradlew
          ./gradlew :service:eureka:server:clean :service:eureka:server:bootJar

      - name: Build Docker image for eureka-service
        run: |
          cd /home/chanhoan/projects/omisys
          docker build \
            -t omisys-eureka-service:latest \
            --build-arg FILE_DIRECTORY=service/eureka/server \
            .

      - name: Deploy eureka-service with docker compose
        run: |
          cd /home/chanhoan/projects/omisys
          docker compose up -d eureka-service
